### ISSUE TITLE
Release on Huggingface Hub

### ISSUE THREAD

**Issue by JoelNiklaus** [multilexsum/dataset#1]
Hi,
Great dataset. I am looking forward to evaluate on it. Will it be released on huggingface hub directly as well?
Cheers,
Joel

**Comment by lolipopshock** [comment]
Thank you @JoelNiklaus ! Yes, releasing Multi-LexSum on HF datasets will be my top priority after my returning from vacation in 2 weeks.

**Comment by JoelNiklaus** [comment]
Great! :)
Enjoy!

**Comment by lolipopshock** [comment]
Resolved in #2; please use the version on https://huggingface.co/datasets/allenai/multi_lexsum . Thanks!

**Comment by JoelNiklaus** [comment]
Great, I will. Thanks
